project:
  type: book
  output-dir: docs
  render: 
    - index.qmd
    - landscape.qmd
    - project-checklist.qmd


book:
  title: "Machine Learning Notebook"
  author: "Nguyen Cao Duc Huy"
  date: "1/02/2024"
  page-footer:
    left:
      Machine Learning Notebook was written by Nguyen Cao Duc Huy
  sidebar:
    logo: images/cover.png
  chapters:
    - index.qmd
    - landscape.qmd
    - project-checklist.qmd
    - regression.qmd
    - gradient-descent.qmd
    - hands-on-regression.qmd
    - classification.qmd
    - hands-on-classification.qmd
    - svm.qmd
    - decision-tree.qmd
    - dimensionality-reduction.qmd
    - part: Appendix
      chapters: 
        - metrics.qmd
    
      

bibliography: references.bib

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    author-meta: "Nguyen Cao Duc Huy"
    callout-appearance: simple

editor: visual

jupyter: dhuy


